nome = input(' Digite seu nome completo: ').strip()
print(' Analisando seu nome...')
print(f'Seu nome em letras maiusculas é {nome.upper()}')
print(f'Seu nome em letras minusculas é {nome.lower()}')
print(f'seu nome tem {len(nome) - nome.count(" ")} letras')
print(f'seu primeiro nome tem {nome.find(" ")} ')
separa = nome.split()
print(f'Seu primeiro nome é {separa[0]} e ele tem {len(separa[0])}')
print(f' seu segundo nome é {separa[1]} e ele tem {len(separa[1])} ')